"""Add electronics table

Revision ID: b50f4439c24c
Revises: 2e1124627258
Create Date: 2025-08-07 09:11:55.369303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50f4439c24c'
down_revision = '2e1124627258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronics', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
