"""Add image_filename field to products

Revision ID: fff4be152975
Revises: c6bcba3bb894
Create Date: 2025-09-11 10:13:39.221674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff4be152975'
down_revision = 'c6bcba3bb894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic_filename')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
